### ISSUE TITLE
Either Left/Right check for null input

### ISSUE THREAD

**Issue by thedillonb** [louthy/csharp-monad#5]
It may be helpful to `Assert`, or even put a null check in for the input of `Either<>.Left()` and `Either<>.Right()` methods. For example, it just took me 20 minutes to find that someone put:

```return Either.Right<ResponseData, Policy?>(null);```

The exception stack trace was no help because this gets evaluated deep within the function tree:

```
Object reference not set to an instance of an object.

   at Monad.Either.<>c__DisplayClass4`2.<Right>b__3()
   at Monad.EitherExt.<>c__DisplayClass27`4.<SelectMany>b__26()
   at Monad.EitherExt.<>c__DisplayClass27`4.<SelectMany>b__26()
   at Monad.EitherExt.<>c__DisplayClass27`4.<SelectMany>b__26()
   at Monad.EitherExt.<>c__DisplayClass27`4.<SelectMany>b__26()
   at Monad.EitherExt.<>c__DisplayClass24`3.<Select>b__23()
   at Monad.EitherExt.<>c__DisplayClass24`3.<Select>b__23()
   at Monad.EitherExt.<>c__DisplayClass24`3.<Select>b__23()
   at Monad.EitherExt.Left[L,R](Either`2 m)
   at Monad.EitherExt.<>c__DisplayClass7`3.<MatchLeft>b__6()
   at VP.VPay.Core.CheckoutSessions.Handlers.UpdateCheckoutSessionPaymentAccountHandler`3.Handle(UpdateCheckoutSessionPaymentAccountCommand`2 request) in d:\git\vpay.payment.core\VP.VPay.Core\CheckoutSessions\Handlers\UpdateCheckoutSessionPaymentAccountHandler.cs:line 62
```

Ouch. No help there.

**Comment by louthy** [comment]
I've just added a few, but I don't currently have time to go through all missing null checks.  Feel free to do a pull request if you need this covered quicker.

**Comment by louthy** [comment]
Ok,you can slightly ignore my last comment.  I just did a blitz through the monad types sorting out the null checks.  The only monad I didn't update is Parser, but from memory that's pretty well covered already.
